apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oaappconfig
  name: oaappconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oaappconfig
  template:
    metadata:
      labels:
        app: oaappconfig
    spec:
      containers:
      - image: hereyourimage.azurecr.io/oawebappconfig
        name: oaappconfig
        env:
        - name: APPCONFIG_CS
          value: "{APPCONFIG_CS}"
        - name: APPCONFIG_KEY
          value: "{APPCONFIG_KEY}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5141
