apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appconfig

resources:
- deploy-webapp.yaml
- service-webapp.yaml

images:
- name: hereyouracr.azurecr.io/oawebappconfig
  newTag: 5141
