apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy-webapp.yaml
- service-webapp.yaml

images:
- name: appconfig
  newName: hereyouracr.azurecr.io/oawebappconfig
  newTag: 5141
