apiVersion: v1
kind: Service
metadata:
    name: oaappconfig
    labels:
        app: oaappconfig
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 5141
      protocol: TCP
      name: http
    selector:
        app: oaappconfig
