name: 1 Deploy Infra (AKS and App Configuration)

on: workflow_dispatch

env:
  AZURE_REGION: eastus
  AZURE_RG: oa-poc-rg
  AKS_CLUSTER_NAME: spAKSCluster
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

jobs:
  deploy-bicep-template:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure RG
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create --location ${{ env.AZURE_REGION }} --name ${{ env.AZURE_RG }}  

      # Deploy Bicep file
    - name: Deploy App Config
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURE_RG }}
        template: ./IaC/appconfig/main.bicep
        parameters: ./IaC/appconfig/azuredeploy.parameters.json
        deploymentName: appconfig-deployment
        failOnStdErr: false

    - name: Deploy AKS
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURE_RG }}
        template: ./IaC/aks/main.bicep
        parameters: ./IaC/aks/azuredeploy.parameters.json
        deploymentName: aks-deployment
        failOnStdErr: false
