b name: 5 Deploy Web App

on: [workflow_dispatch]

env:
  CLUSTER_NAME: AKSClsuter-Demo
  AZURE_RG: oa-poc-rg
  NAMESPACE: appconfig
  IMAGE_NAME: oawebappconfig
  AZURE_CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  KUSTOMIZE_PATH: './yaml_files/'
  TAG: 5141
  APP_NAME: oaappconfig
  PREFIX: Pod2
  APPCONFIG_CS: ${{ secrets.APPCONFIG_CS }}

jobs:
  deploy-webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.AZURE_RG }}

    - uses: azure/setup-kubectl@v2.0

    - name: Set up Kustomize
      run: |-
        cd yaml_files
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        ./kustomize --help

    - name: Deploy Web App
      run: |-
        kubectl create ns ${{ env.NAMESPACE }}
        kubectl create deploy ${{ env.APP_NAME }} --image=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} --env="APPCONFIG_CS=${{ env.APPCONFIG_CS }}" --env="APPCONFIG_KEY=${{ env.PREFIX }}" -n ${{ env.NAMESPACE }}
        kubectl expose deployment ${{ env.APP_NAME }} --type=LoadBalancer --name=${{ env.APP_NAME }} --port=80 --target-port=${{ env.TAG }} 
       

    # Deploy  Web App with Kustomize
#    - name: Deploy
#      run: |-
#        # replacing the image name in the k8s template
#        cd yaml_files
#        ./kustomize edit set image hereyourimage.azurecr.io/oawebappconfig=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
#        ./kustomize build . | kubectl apply -f - 
