name: 2 Create and Set Keys

on: workflow_dispatch

env:
  AZURE_REGION: eastus
  AZURE_RG: oa-poc-rg
  APP_CONFIGURATION_NAME: oaappconfig02
  MESSAGE: 'OA was here. V1.0'
  

jobs:
  deploy-bicep-template:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Keys
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:BackgroundColor --value red
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:FontColor --value white
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:FontSize --value 20
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod1:Settings:Message --value ${{ env.MESSAGE }}
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod1:Settings:Sentinel --value 2
