name: 2 Create and Set Keys

on: workflow_dispatch

env:
  AZURE_REGION: eastus
  AZURE_RG: oa-poc-rg
  APP_CONFIGURATION_NAME: oaappconfig02
  SENTINEL: 2
  

jobs:
  set-keys-appconfig:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Keys
      env:
        MESSAGE: "OA was here. V1.0"
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:BackgroundColor --value red --yes
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:FontColor --value white --yes
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:FontSize --value 20 --yes
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:Message --value "$MESSAGE" --yes
          az appconfig kv set -n ${{ env.APP_CONFIGURATION_NAME }} --key Pod2:Settings:Sentinel --value ${{ env.SENTINEL }} --yes
