name: 4 Udpate AKS with ACR

on: workflow_dispatch

env:
  AZURE_RG: oa-poc-rg
  AKS_CLUSTER_NAME: AKSCluster-Demo
  ACR_NAME: ${{ secrets.ACR_NAME_OLD }}

jobs:
  update-aks:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Udpate AKS with ACR
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks update -g ${{ env.AZURE_RG }} -n ${{ env.AKS_CLUSTER_NAME }} --attach-acr ${{ env.ACR_NAME }}
